=== ArvinZJC/BUAAHND_G3T2_SDD/WebContent/L8/L8_1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT classes (class+)>
<!ELEMENT class ((name|(firstName,lastName)),tel, (weChat|email|qq))>
<!ELEMENT name (#PCDATA)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT weChat (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT qq (#PCDATA)>

<!ATTLIST class id CDATA #REQUIRED>
<!ATTLIST class monitor IDREF #REQUIRED>
<!ATTLIST class major CDATA #REQUIRED>
<!ATTLIST class college CDATA #FIXED "buaa">
<!ATTLIST name sid ID #REQUIRED>
<!ATTLIST name gender (F|M) "M">
<!ATTLIST firstName fsid ID #REQUIRED>
<!ATTLIST firstName fgender (F|M) "M">

=== ArvinZJC/BUAAHND_G3T2_SDD/WebContent/L8/L8_1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE classes SYSTEM "L8_1.dtd">
<classes>
	<class id="1" monitor="c1-7" major="SD">
		<firstName fsid="c1-7">Arvin</firstName>
		<lastName>Zhao</lastName>
		<tel>741741741</tel>
		<weChat>test</weChat>
	</class>
	<class id="2" monitor="c2-1" major="SD">
		<name sid="c2-1" gender="F">James</name>
		<tel>741741742</tel>
		<email>test@qq.com</email>
	</class>
</classes>
